# Generated by Django 4.1.5 on 2023-02-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_country_interest_remove_yatri_bio_yatri_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yatri',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
